# ---------------------------------------
# Fenn Configuration (Modify Carefully)
# ---------------------------------------

project: cart_racing

# ---------------------------
# Logging & Tracking
# ---------------------------

logger:
  dir: /media/kirito/arusso/rl/logger

# ---------------------------------------
# Example of User Section
# ---------------------------------------
model:
  backbone: True

env:
  max_episode_steps: 500

train:
  lr: 0.001

sampling:
  percentile: 70
  batch_size: 8
  epochs: 100

export:
  tensorboard: /media/kirito/arusso/rl/runs
  video_folder: /media/kirito/arusso/rl/video
  model: /media/kirito/arusso/rl/car_racing_resnet18.pth