# ---------------------------------------
# Fenn Configuration (Modify Carefully)
# ---------------------------------------

project: cart_racing

# ---------------------------
# Logging & Tracking
# ---------------------------

logger:
  dir: logger

# ---------------------------------------
# User Section
# ---------------------------------------

env:
  max_episode_steps: 2000

train:
  lr: 0.001

sampling:
  percentile: 70
  batch_size: 50
  epochs: 100

export:
  tensorboard: runs
  video_folder: video
  model: cart_pole.pth